### ISSUE TITLE
BLB 命名优化

### ISSUE THREAD

**Issue by tianyuansun** [baidu/cloud-provider-baiducloud#110]
BLB 命名规则

CCE/svc/cluster-id/namespace/service-name

**Comment by hello2mao** [comment]
@tianyuansun BLB的名字有长度限制，尽量简化，建议保留cluster-id/namespace/service-name的方式

可以看下这个issue：#58，其中名字是：c-H8PjVxox/tangzhiyi-test-namespace-randomra/deployment-ifr-5epdvj6w566k0025
