### ISSUE TITLE
create LB Service with two LB

### ISSUE THREAD

**Issue by hello2mao** [baidu/cloud-provider-baiducloud#63]
svc创建出两个blb
![image](https://user-images.githubusercontent.com/8265961/54984877-bcccf100-4fea-11e9-803e-2b7c14c81c06.png)
![image](https://user-images.githubusercontent.com/8265961/54985265-75933000-4feb-11e9-9eac-4ab15fac1827.png)
[ccm.log](https://github.com/baidu/cloud-provider-baiducloud/files/3007348/ccm.log)

**Comment by hello2mao** [comment]
条件：新添加的节点被系统感知到，此时恰好有lb service创建，就会double ensure
![image](https://user-images.githubusercontent.com/8265961/54985522-e5a1b600-4feb-11e9-80e0-f0b550130397.png)

**Comment by wccsama** [comment]
尝试复现失败，hold on。
