### ISSUE TITLE
指定LB Service的BLB

### ISSUE THREAD

**Issue by hello2mao** [baidu/cloud-provider-baiducloud#70]

**Comment by hello2mao** [comment]
/assign @wccsama

建议先试用下 https://github.com/baidu/cloud-provider-baiducloud/blob/master/docs/tutorial_zh-CN.md 内的功能。

**Comment by wccsama** [comment]
Hi hello2mao, in "load_balancer_blb.go", cloud you please tell me why there are double check the "serviceAnnotation.LoadBalancerId" in line 25 and 41? Thanks.
