### ISSUE TITLE
创建service时，添加了不支持的annotation导致EIP重复

### ISSUE THREAD

**Issue by hello2mao** [baidu/cloud-provider-baiducloud#82]
添加如下annotation会导致创建出来的LB Service的EIP重复：
```
service.beta.kubernetes.io/cce-load-balancer-id
```

**Comment by wccsama** [comment]
@hello2mao 在指定BLBid时，cce-load-balancer-id注释不会对创建LB产生影响。这里说的EIP的重复，应该是未指定BLB时，使用该字段也能创建LB吧？

**Comment by hello2mao** [comment]
fixed in #86
/close

**Comment by wccsama** [comment]
建议将LoadBalancerId改名CceAutoAdd，这个字段用于在执行期间记录lb的创建记录，防止重复创建lb。
