### ISSUE TITLE
给指定BLB增加测试case，并集成进测试脚本中

### ISSUE THREAD

**Issue by hello2mao** [baidu/cloud-provider-baiducloud#89]

**Comment by hello2mao** [comment]
@wccsama 
集成测试的case目前看还是需要的，得尽快加进去并自测下，请确保：
（1）自测前后，在console上验证没有EIP、BLB泄露
（2）自测过程中，记录CCM日志，完成自测后，过滤日志保证CCM无异常日志
（3）覆盖尽可能多的情况，正常、异常

**Comment by wccsama** [comment]
(1)中EIP与BLB泄露是什么情况，可以详细说下嘛。

**Comment by hello2mao** [comment]
> (1)中EIP与BLB泄露是什么情况，可以详细说下嘛。

@wccsama 之前经常出现的case是，由于种种原因，删除service后，发现console上有EIP或者BLB还残留着，没有自动删除，还继续扣用户的钱。你可以看到，你的代码中，是先删除BLB后删除EIP，那么如果删除BLB成功后，出现bug，没有删除EIP，则EIP就可能泄漏。

**Comment by wccsama** [comment]
（1）中说明的泄露问题，可以在delete的最后检查一遍eip与blb，倘若未删除成功应该提醒用户。不能在出错时只是返回错误，这里涉及到一个重试的issue #84。
（2）关于日志的问题我还在学习中，个人设想每次用户执行的指令时，ccm产生日志都应该单独保存在一个文件中（一条指令对应一个日志），且日志保存一定时间，定期删除更新。

**Comment by hello2mao** [comment]
> （2）关于日志的问题我还在学习中，个人设想每次用户执行的指令时，ccm产生日志都应该单独保存在一个文件中（一条指令对应一个日志），且日志保存一定时间，定期删除更新。

目前是journald托管，会定时清理的，你可以了解下
