### ISSUE TITLE
update node 优化

### ISSUE THREAD

**Issue by hello2mao** [baidu/cloud-provider-baiducloud#91]
![image](https://user-images.githubusercontent.com/8265961/58540089-42f3f680-822b-11e9-89db-dae5b7bcca30.png)

**Comment by wccsama** [comment]
@hello2mao ，请问这段代码在哪里，图片太糊。

**Comment by hello2mao** [comment]
> @hello2mao ，请问这段代码在哪里，图片太糊。

@wccsama  
https://github.com/baidu/cloud-provider-baiducloud/blob/442c1f7ab9fba3f63d32ab54b525d012a632d1c8/pkg/cloud-provider/routes.go#L214
